### ISSUE TITLE
export IDENTIFIER_URI=$(az ad app show --id $API_APP_ID --query identifierUris[0] -o tsv) does not work

### ISSUE THREAD

**Issue by NathanDotTo** [mspnp/serverless-reference-implementation#127]
This command form:

```
export IDENTIFIER_URI=$(az ad app show --id $API_APP_ID --query identifierUris[0] -o tsv)
```

Produces this error:

```
zsh: no matches found: identifierUris[0]
```

But this form of the command seems to work:

```
export IDENTIFIER_URI=$(az ad app show --id $API_APP_ID --query identifierUris -o tsv)
```

**Comment by v-fearam** [comment]
I wanted to inform you that the issue has been addressed in the pull request #125. I will proceed to close the ticket. However, if you encounter any further issues or have additional feedback, please feel free to open a new ticket.
