### ISSUE TITLE
az cdn profile create --location $LOCATION --resource-group $RESOURCEGROUP --name $CDN_NAME does not work

### ISSUE THREAD

**Issue by NathanDotTo** [mspnp/serverless-reference-implementation#128]
This command does not work:

```
az cdn profile create --location $LOCATION --resource-group $RESOURCEGROUP --name $CDN_NAME
```

Because, I think, the --sku defaults to `Standard_Akamai`, but Akamai is no longer supported:

https://aka.ms/azure-cdn-akamai-retirement

So, the command should be, I think:

```
az cdn profile create --location northeurope --resource-group $RESOURCEGROUP --sku Standard_Microsoft --name $CDN_NAME
```

This is really a problem with the CLI command defaults though.

**Comment by v-fearam** [comment]
I wanted to inform you that the issue has been addressed in the pull request #125. I will proceed to close the ticket. However, if you encounter any further issues or have additional feedback, please feel free to open a new ticket.
