### ISSUE TITLE
az ad sp create-for-rbac --role="Contributor" --sdk-auth does not work

### ISSUE THREAD

**Issue by NathanDotTo** [mspnp/serverless-reference-implementation#130]
```
export SP_DETAILS=$(az ad sp create-for-rbac --role="Contributor" --sdk-auth)
WARNING: Option '--sdk-auth' has been deprecated and will be removed in a future release.
ERROR: Usage error: To create role assignments, specify both --role and --scopes.
```

In any case, this should probably be a managed identity. In which case we need to know how to get the JSON body for that managed identity.

**Comment by v-fearam** [comment]
I wanted to inform you that the issue has been addressed in the pull request #125. I will proceed to close the ticket. However, if you encounter any further issues or have additional feedback, please feel free to open a new ticket.
