### ISSUE TITLE
Make app setting names consistent

### ISSUE THREAD

**Issue by MikeWasson** [mspnp/serverless-reference-implementation#15]
Our custom app setting names should use THIS_FORMAT and not CamelCase

- EventHubConnection
- EventHubConsumerGroup
- EventHubName
- DeadLetterStorage

Also, CosmosDBDataBase and CosmosDBCollection in azuredeploy-slots.json

Note: "AzureWebJobsStorage" is defined by the platform, so don't change that one

**Comment by jocontr** [comment]
Fixed and merged.
