### ISSUE TITLE
Potential NullPointerException in DroneTelemetry example

### ISSUE THREAD

**Issue by micdah** [mspnp/serverless-reference-implementation#23]
There seems to be a potential  `NullPointerException` in [RawTelemetryFunction.cs](https://github.com/mspnp/serverless-reference-implementation/blob/master/src/DroneTelemetry/DroneTelemetryFunctionApp/RawTelemetryFunction.cs), specifically if deserialization fails then `deviceState` is null when calling:

```cs
await stateChangeProcessor.UpdateState(deviceState, logger);
```

This method doesn't handle the parameter being null (_and it probably shouldn't either, shouldn't be called at all in this case_):
```cs
public async Task<ResourceResponse<Document>> UpdateState(DeviceState source, ILogger log)
{
  log.LogInformation("Processing change message for device ID", source.DeviceId);
  // ...
}     
```

I tried to fork the repo to make a pull request, but seems I am not allowed to do so, it is deleted immediately after I try to fork the repo, each time.

**Comment by ferantivero** [comment]
thanks for contributing @micdah, please give another try creating that fork. I pretty much think it could've being related to some GitHub issues in the last couple of hours.
