### ISSUE TITLE
[dronestatus] inconsistent unauthorized v1 and v2 response

### ISSUE THREAD

**Issue by ferantivero** [mspnp/serverless-reference-implementation#24]
I know v1 & v2 responses shouldn't necessarily have to match. But I think we can benefit from it provided we follow same v2 custom response message approach in v1. For instance while deploying is a first response we could use to validate the steps are being executed as expected. 

If not, we could consider just return empty in V2 as in V1.

Actual
1. V1 response: 
    HTTP/1.1 401 Unauthorized -content-length: 0

2. V2 response:
     HTTP/1.1 401 Unauthorized - content-length: 31
     {
        "error": "Unauthorized"
     }

Expected
V1 and V2 could match in some way or the another.

**Comment by jocontr** [comment]
After review; noticed that this issue has been addressed.
