### ISSUE TITLE
Installation issue: Deployment instructions should specify the event hub connection string

### ISSUE THREAD

**Issue by brianensink** [mspnp/serverless-reference-implementation#33]
I am attempting to follow the deployment instructions but I  don't know how to find the `event-hub-connection-string` needed here: https://github.com/mspnp/serverless-reference-implementation/blob/master/src/readme.md#build-and-run-the-device-simulator

```
export EVENT_HUB_CONNECTION_STRING=<event-hub-connection-string> # Use the 'send' authorization rule
```

**Comment by ferantivero** [comment]
hi @brianensink please let's give a try with the following:

```
# list eh namespace name(s)
az eventhubs namespace list \
     -g $RESOURCEGROUP \
     --query [].name

# list the send keys
az eventhubs eventhub authorization-rule keys list \
     -g $RESOURCEGROUP \
     --eventhub-name $APPNAME-eh  \
     --namespace-name <use-the-name-from-previous-step> \
     -n send
```

**Comment by brianensink** [comment]
Thanks! I can't try that right now though because I tore down the resource group when I noticed the  cost was $84.13 for less than 36 hours. It would be nice to have smaller cheaper reference architectures that could be deployed and learned from without incurring $1500 to $2000 a month in costs.

**Comment by ferantivero** [comment]
we really appreciate your feedback @brianensink, definitely this will be shared with the team. Thanks again,

cc/ @MikeWasson
