### ISSUE TITLE
Create Cosmos DB collection in template

### ISSUE THREAD

**Issue by MikeWasson** [mspnp/serverless-reference-implementation#40]
Currently the deployment creates the collection via CLI. Cosmos DB now supports creating these via template.

**Comment by ferantivero** [comment]
I thought it was no possible to create Cosmos DB db and/or containers using ARM.

**Comment by jocontr** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID [218978](https://dev.azure.com/ceapex/pnp/_workitems/edit/218978)
