### ISSUE TITLE
[readme.md] ResourceNotFound - 'Microsoft.Web/sites/$APPNAME-ds-funcapp'

### ISSUE THREAD

**Issue by petertuton** [mspnp/serverless-reference-implementation#61]
In the section, "Configure Azure AD authentication in the Function App" the commend returns the error: 
`ResourceNotFound - The Resource 'Microsoft.Web/sites/$APPNAME-ds-funcapp' under resource group '$RESOUCEGROUP' was not found.`

This is because it refers to `--name $APPNAME-ds-funcapp` instead of `--name $DRONE_STATUS_FUNCTION_APP_NAME `.

**Comment by ferantivero** [comment]
thanks for the feedback @petertuton, please let me share this with the team so we can review this. PRs are more than welcome 😸 

cc/ @MikeWasson

**Comment by jocontr** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID [218980](https://dev.azure.com/ceapex/pnp/_workitems/edit/218980)

**Comment by kirpasingh** [comment]
Thank you @petertuton! This issue is now closed with PR #66
