### ISSUE TITLE
Use RBAC roles instead of Authorization rules for function app access to event hub

### ISSUE THREAD

**Issue by marnheus** [mspnp/serverless-reference-implementation#77]
In my company a policy has been deployed that disallow the usage of sas keys to access event hub.
I'll need to use RBAC role assignment to access the event hub from the managed identity of my app.

I'm thinking of proposing a version of this architecture using rbac and managed identity to access the event hub. That would mean modification of the arm template + for the access code.

Would it be of value?

**Comment by marnheus** [comment]
Actually this is not feasible while the Azure Function event hub binding is updated to support managed identities connection. Once this is done, I'll come back to this.

**Comment by v-fearam** [comment]
Hi @marnheus 
I really appreciate your initiative. The use of managed identity is recommended when possible.
Not all services support managed identity (https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/services-support-managed-identities). However, Azure Function supports it. 

Are you going to propose a change? I think it would be valuable.
I will close the issue and you can open a PR with your proposal anytime.
